export const orders = [
  {
    id: 1,
    car: 'Geely Coolray',
    number: 'т158оо77',
    client: 'Попов Виктор Иванович',
    master: 'Антонов Михаил Иванович',
    date: '01-01-2022',
  },
  {
    id: 2,
    car: 'Cherry Tiggo4',
    number: 'м548оо144',
    client: 'Валерьев Денис Петрович',
    master: 'Васильев Александр Олегович',
    date: '02-01-2022',
  },
  {
    id: 3,
    car: 'Tank 300',
    number: 'т158оо77',
    client: 'Попов Виктор Иванович',
    master: 'Антонов Михаил Иванович',
    date: '03-01-2022',
  },
  {
    id: 4,
    car: 'Toyota Camry',
    number: 'в123ав45',
    client: 'Иванов Иван Иванович',
    master: 'Петров Петр Петрович',
    date: '04-01-2022',
  },
  {
    id: 5,
    car: 'Ford Focus',
    number: 'с234сс77',
    client: 'Сидорова Анна Васильевна',
    master: 'Кузнецов Дмитрий Сергеевич',
    date: '05-01-2022',
  },
  {
    id: 6,
    car: 'Honda Civic',
    number: 'н345мс98',
    client: 'Петрова Елена Игоревна',
    master: 'Смирнов Артем Владимирович',
    date: '06-01-2022',
  },
  {
    id: 7,
    car: 'BMW X5',
    number: 'к456рт35',
    client: 'Козлов Алексей Николаевич',
    master: 'Федорова Мария Петровна',
    date: '07-01-2022',
  },
  {
    id: 8,
    car: 'Mercedes-Benz E-Class',
    number: 'с567см21',
    client: 'Николаев Владимир Александрович',
    master: 'Андреев Антон Игоревич',
    date: '08-01-2022',
  },
  {
    id: 9,
    car: 'Volkswagen Golf',
    number: 'о678ра15',
    client: 'Павлов Александр Дмитриевич',
    master: 'Григорьев Артем Степанович',
    date: '09-01-2022',
  },
  {
    id: 10,
    car: 'Audi A4',
    number: 'а789рк79',
    client: 'Соколова Ольга Викторовна',
    master: 'Комаров Илья Александрович',
    date: '10-01-2022',
  },
  {
    id: 11,
    car: 'Hyundai Sonata',
    number: 'к890ек05',
    client: 'Морозова Анастасия Сергеевна',
    master: 'Иванова Елена Васильевна',
    date: '11-01-2022',
  },
  {
    id: 12,
    car: 'Kia Sportage',
    number: 'у901ум82',
    client: 'Титов Павел Владимирович',
    master: 'Степанов Сергей Алексеевич',
    date: '12-01-2022',
  },
  {
    id: 13,
    car: 'Nissan Qashqai',
    number: 'м012ау99',
    client: 'Федотова Наталья Игоревна',
    master: 'Богданов Владислав Васильевич',
    date: '13-01-2022',
  },
  {
    id: 14,
    car: 'Chevrolet Cruze',
    number: 'с123ус33',
    client: 'Гусева Татьяна Алексеевна',
    master: 'Лебедев Максим Артемович',
    date: '14-01-2022',
  },
];

export const receipts = [
  {
    id: 1,
    vendor: 'Амтел',
    counterparty: 'Аларм-Моторс Озерки',
    date: '28.03.2024',
    receiver: 'Климовский Иван Александрович',
  },
  {
    id: 2,
    vendor: 'Автоконтракты',
    counterparty: 'Аларм-Моторс Юго-Запад',
    date: '29.03.2024',
    receiver: 'Петрова Елена Викторовна',
  },
  {
    id: 3,
    vendor: 'Автомобильные запчасти',
    counterparty: 'Аларм-Моторс Лахта',
    date: '30.03.2024',
    receiver: 'Иванов Андрей Сергеевич',
  },
  {
    id: 4,
    vendor: 'Автофемели',
    counterparty: 'Аларм-Комтранс',
    date: '31.03.2024',
    receiver: 'Смирнова Ольга Николаевна',
  },
  {
    id: 5,
    vendor: 'Иксора-Трейд',
    counterparty: 'Аларм-Моторс Озерки',
    date: '01.04.2024',
    receiver: 'Павлов Владимир Игоревич',
  },
  {
    id: 6,
    vendor: 'Евро-Авто',
    counterparty: 'Аларм-Моторс Юго-Запад',
    date: '02.04.2024',
    receiver: 'Кузнецов Алексей Валентинович',
  },
  {
    id: 7,
    vendor: 'Амтел',
    counterparty: 'Аларм-Моторс Лахта',
    date: '03.04.2024',
    receiver: 'Соколова Елена Александровна',
  },
  {
    id: 8,
    vendor: 'Автоконтракты',
    counterparty: 'Аларм-Моторс Озерки',
    date: '04.04.2024',
    receiver: 'Борисов Дмитрий Павлович',
  },
  {
    id: 9,
    vendor: 'Автомобильные запчасти',
    counterparty: 'Аларм-Моторс Юго-Запад',
    date: '05.04.2024',
    receiver: 'Григорьева Наталья Сергеевна',
  },
  {
    id: 10,
    vendor: 'Автофемели',
    counterparty: 'Аларм-Комтранс',
    date: '06.04.2024',
    receiver: 'Титов Александр Игоревич',
  },
  {
    id: 11,
    vendor: 'Иксора-Трейд',
    counterparty: 'Аларм-Моторс Лахта',
    date: '07.04.2024',
    receiver: 'Федоров Александр Павлович',
  },
  {
    id: 12,
    vendor: 'Евро-Авто',
    counterparty: 'Аларм-Моторс Озерки',
    date: '08.04.2024',
    receiver: 'Калинин Алексей Иванович',
  },
  {
    id: 13,
    vendor: 'Амтел',
    counterparty: 'Аларм-Моторс Лахта',
    date: '09.04.2024',
    receiver: 'Сидорова Мария Дмитриевна',
  },
  {
    id: 14,
    vendor: 'Евро-Авто',
    counterparty: 'Аларм-Комтранс',
    date: '10.04.2024',
    receiver: 'Иванов Игорь Петрович',
  },
];

export const nomenclature = [
  {
    id: 1,
    nomenclature: 'Колодки задние TRW',
    quantity: 5.0,
    unit: 'шт.',
    price: 125.0,
  },
  {
    id: 2,
    nomenclature: 'Двигатель Ford Duratec',
    quantity: 1.0,
    unit: 'шт.',
    price: 1150.0,
  },
  {
    id: 3,
    nomenclature: 'Моторное масло Castrol EDGE',
    quantity: 4.5,
    unit: 'л',
    price: 143.0,
  },
  {
    id: 4,
    nomenclature: 'Аккумуляторная батарея Bosch S4',
    quantity: 1.0,
    unit: 'шт.',
    price: 155.0,
  },
  {
    id: 5,
    nomenclature: 'Шина Michelin Pilot Sport 4',
    quantity: 4.0,
    unit: 'шт.',
    price: 130.0,
  },
  {
    id: 6,
    nomenclature: 'Тормозной диск Brembo',
    quantity: 2.0,
    unit: 'шт.',
    price: 180.0,
  },
  {
    id: 7,
    nomenclature: 'Фильтр воздушный MANN-FILTER',
    quantity: 1.0,
    unit: 'шт.',
    price: 173.0,
  },
  {
    id: 8,
    nomenclature: 'Антифриз ZIC G-05',
    quantity: 5.0,
    unit: 'л',
    price: 90.0,
  },
  {
    id: 9,
    nomenclature: 'Ремень ГРМ Gates',
    quantity: 1.0,
    unit: 'шт.',
    price: 127.0,
  },
  {
    id: 10,
    nomenclature: 'Фара левая Hella',
    quantity: 1.0,
    unit: 'шт.',
    price: 127.0,
  },
  {
    id: 11,
    nomenclature: 'Радиатор охлаждения Nissens',
    quantity: 1.0,
    unit: 'шт.',
    price: 127.0,
  },
  {
    id: 12,
    nomenclature: 'Подушка двигателя Lemforder',
    quantity: 2.0,
    unit: 'шт.',
    price: 127.0,
  },
  {
    id: 13,
    nomenclature: 'Топливный насос Bosch',
    quantity: 1.0,
    unit: 'шт.',
    price: 127.0,
  },
  {
    id: 14,
    nomenclature: 'Свеча зажигания NGK',
    quantity: 4.0,
    unit: 'шт.',
    price: 127.0,
  },
];
